### PR TITLE
修复在Rails5下的冲突问题。不再重写blank?方法，而是改用新方法j_blank

### PR DESCRIPTION
**Pull request by JasonSi**
试了一下这样子的确解决了冲突问题。 我觉得还是尽量不要monkey patch比较好

### CODE REVIEW

**Comment by helperhaps** [comment]
It's not monkey-patch,It's  Refinement. It has namespace.

**Comment by JasonSi** [comment]
Sorry for my mistake. However it affected other gems. 

——Jason

**Comment by helperhaps** [comment]
Yep, It is my mistake. I will fix it as soon as possibe

**Comment by JasonSi** [comment]
Thank you very much.

**Comment by helperhaps** [comment]
So, thank you for your PR, but I will  not merge it

**Pull request closed without merging**
